// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Vehicle_Assembly.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250304052505_migration_05")]
    partial class migration_05
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vehicle_Assembly.Models.AdminModel", b =>
                {
                    b.Property<int>("NIC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NIC"));

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("firstname")
                        .HasColumnType("longtext");

                    b.Property<string>("lastname")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("password")
                        .HasColumnType("longblob");

                    b.HasKey("NIC");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("Vehicle_Assembly.Models.AssembleModel", b =>
                {
                    b.Property<int>("vehicle_id")
                        .HasColumnType("int");

                    b.Property<int>("NIC")
                        .HasColumnType("int");

                    b.Property<int>("assignee_id")
                        .HasColumnType("int");

                    b.Property<string>("attachment_path")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("vehicle_id", "NIC");

                    b.HasIndex("NIC");

                    b.HasIndex("assignee_id");

                    b.ToTable("assembles");
                });

            modelBuilder.Entity("Vehicle_Assembly.Models.LoginInfoModel", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("jwt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("email");

                    b.ToTable("logininfo");
                });

            modelBuilder.Entity("Vehicle_Assembly.Models.VehicleModel", b =>
                {
                    b.Property<int>("vehicle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("vehicle_id"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("engine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("vehicle_id");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("Vehicle_Assembly.Models.WorkerModel", b =>
                {
                    b.Property<int>("NIC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NIC"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("job_role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NIC");

                    b.ToTable("worker");
                });

            modelBuilder.Entity("Vehicle_Assembly.Models.AssembleModel", b =>
                {
                    b.HasOne("Vehicle_Assembly.Models.WorkerModel", "Worker")
                        .WithMany()
                        .HasForeignKey("NIC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicle_Assembly.Models.AdminModel", "Admin")
                        .WithMany()
                        .HasForeignKey("assignee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicle_Assembly.Models.VehicleModel", "Vehicle")
                        .WithMany()
                        .HasForeignKey("vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Vehicle");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
